### ISSUE TITLE
Strange Code coverage percentage

### ISSUE THREAD

**Issue by sas393** [NickHeap2/newman-reporter-openapi#1]
Starange Code coverage percentage when i use reporter openapi (You can see it on screenshot)
![image](https://user-images.githubusercontent.com/48256159/160799281-673a029d-5688-4d4b-af0e-fb98954053d1.png)
.  For example,first line in table`s screen.  What iam doing wrong and why % are so weird? I use OpenAPI 3.0 for test.

**Comment by NickHeap2** [comment]
@sas393 First off try adding '--reporter-openapi-debug true' and see if that helps diagnose things.
If not feel free to send me the debug output and spec (if that's allowed) and I can test it out.

**Comment by sas393** [comment]
@NickHeap2 Thanks for debug command.  I will try to understand by my own firstly with this command.  Maybe it worth to be added in readme.md? (just a proposition). 

P.s. I tried to use .YAML instead of .JSON and it begins to show correct percentage.

**Comment by NickHeap2** [comment]
Thanks @sas393 for trying that out.
I'll take a look at the differences between .yaml and .json and get that working.

**Comment by NickHeap2** [comment]
@sas393 I've found an issue in the reporter percentages code that may have been affecting you. The fix is in the 0.0.7 release.

**Comment by NickHeap2** [comment]
@sas393 going to close this down now.
